### ISSUE TITLE
Incorrect C code generated with IA5String constant

### ISSUE THREAD

**Issue by michalkocon** [ttsiodras/asn1scc#111]
After generating C code with asn.1 constant (`asn1.exe -c String.asn1`):
```
String DEFINITIONS AUTOMATIC TAGS ::= BEGIN

stringConstant IA5String ::= "Constant"

END
```

I get following result: 
`const char stringConstant = "Constant";`

Looks like either `*` or `[]` is missing in generated code.

**Comment by gmamais** [comment]
As a workaround, please define a string type with size constraint and then use this type to define the variable. Eg
String DEFINITIONS AUTOMATIC TAGS ::= BEGIN

MyString ::= IA5String (SIZE(0..100))
stringConstant MyString ::= "Constant"

END

Please note that this is not an issue in ASN1SCC_V4 since this compiler emits the following error
"Declared type may have infinite size. Use size constraints to limit the upper bound"
Forcing user to define first a type.
