### ISSUE TITLE
Incorrect interaction between OPTIONAL and size determinant

### ISSUE THREAD

**Issue by Lurkerpas** [ttsiodras/asn1scc#113]
Given ASN.1:
```
TESTMODULE DEFINITIONS AUTOMATIC TAGS ::= BEGIN

GenericCommand ::= SEQUENCE {
  commandArgument INTEGER OPTIONAL,
  instructions SEQUENCE(SIZE(1..100)) OF INTEGER
}

Command ::= GenericCommand (WITH COMPONENTS {commandArgument PRESENT})

END
```
and ACN:
```
TESTMODULE DEFINITIONS ::= BEGIN

GenericCommand [] {
  commandArgument [],
  n INTEGER[],
  instructions [size n]
}

END
```
when compiling the code to generate HTML ICD, the following error message is produced by asn1scc:
File:testmodule.acn, line:5, the ACN inserted field 'n' is not reference by any other field (e.g. as length determinant or presence determinant etc)

In fact, "n" is used as a size determinant for field "instruction". I believe that this behaviour is incorrect.

**Comment by gmamais** [comment]
This bug, among many others, has been fixed in the V4 of the ASN1 compiler which is available here
https://github.com/ttsiodras/asn1scc/tree/ASN1SCC_V4

Please note that there is a slight change in ACN compare to V3. It is now mandatory for ACN inserted fields to specify the encoding and size attributes. In your case, the ACN grammar must be modified as follows
`GenericCommand [] {
  commandArgument [],
  n INTEGER[**encoding pos-int, size 8**],
  instructions [size n]
}
`
