### ISSUE TITLE
[V4][XML.AST] <CONS> and <WITH_CONS> items are not self-explanatory

### ISSUE THREAD

**Issue by hcorg** [ttsiodras/asn1scc#129]
I guess, that <CONS> are really <Constraints> :) but I have no idea what <WITH_CONS /> is - maybe better name could help future users.

**Comment by gmamais** [comment]
Ok, I will rename CONS to Constraints
and WITH_CONS to WithComponentConstraint.
WITH COMPONENTS constraints  are handled differently because they have no impact on UPER encoding.
e.g.

MYINT ::= (0..1023) -- 10 bits
MYSEQOF ::= SEQUENCE (SIZE(10)) OF MYINT (WITH COMPONT (0..31)) --MYSEQOF will be encoded as 10*10bits = 100 bits even though the allowed values for the integer is 0..31

**Comment by hcorg** [comment]
ooooh, I completely forgot about `WITH COMPONENTS` :D

**Comment by gmamais** [comment]
CONS renamed to Constraints
and 
WITH_CONS to WithComponentConstraints
