### ISSUE TITLE
Missing C function when SIZE constraint is duplicated on a SEQUENCE member

### ISSUE THREAD

**Issue by Glamhoth** [ttsiodras/asn1scc#231]
Let's consider the following ASN.1 file:
```
MYMODULE DEFINITIONS ::= BEGIN

MyArray ::= SEQUENCE (SIZE(20)) OF INTEGER (1..20)

MySeq ::= SEQUENCE
{
    data MyArray(SIZE(20))
}

END
```

C file that is generated from this file, by running
```
$ asn1scc -c -ACN mymodule.asn
```  
tries to call `MySeq_data_elem_Initialize` which was not created
![image](https://user-images.githubusercontent.com/5027115/158176595-52ff39e7-f6cf-4e58-9eb6-e034db762acb.png)

**Comment by usr3-1415** [comment]
Thanks for reporting this, I will look into it.

**Comment by maxime-esa** [comment]
The bug is still present in the latest version (`4.4.0.2`).
There is a workaround however: when using the new `-ig` flag, the generated code is correct (no symbol is missing):
```
const MySeq_data MySeq_data_constant = {.arr  = {[0 ... 20-1] = 1UL }};
const MySeq MySeq_constant = {.data = MySeq_data_constant};

void MySeq_data_Initialize(MySeq_data* pVal)
{
	(void)pVal;
	(*(pVal)) = MySeq_data_constant;
}
```

This flag makes the compiler generate constants to initialize the data structures, instead of code (with loops for the arrays).

**Comment by usr3-1415** [comment]
fixed
